language: java
script:
- wget https://languagetool.org/download/LanguageTool-stable.zip
- unzip LanguageTool-stable.zip
- mv LanguageTool-*/ lt
- ant compile
- cd lt && tar -zcvf ../lt.tar.gz * && cd ..
deploy:
  provider: releases
  api_key:
    secure: p8x/WY4alMLYhIYBF+HqSVEShPN0JCaW1KgLHJkkhRyDJ0/ppEOzvZl8TVvqgBpBjOn3oJp/7OrQoSKDOPLgo62CBAA/d8gjT66Viq1fKjPduEVl3YmdstfonrC7b6WOsQTR64j/XBiZLzXGes5qm9sxW7uIk/htJFMQ1WI54VmjTbUhyr5E3J1Zz441S0VHGHLmIVkK3AGV8PY/HzBr42oiBhDdAR0mrCnmV3G5mW89bA6FYbJ7Idsnf72G69Md0dzYatMrUlk6B03ajgPs4pPVfsBhNy6fgGIiVVBLF+7o7J5EXCc7a84LIcZAjr7WhGyexo4om7xKwILPQx3rW3d2vkDkeDQiysE/9yVs8oaYOv5OM2PYCm2m2kK62k7O2wpjPfu0mlBL4mU7SSNZ2BOs0NyDW1OrJLnaFEj7GSxc9Hb8LJBuWq/e/UjIaU8NUOaM55CczrUtdyGx84lE7ow5FBPkqLLr96SrX5JupVIZFyO9Owa0z8C1uuE8Ul4aQIuR19iEt12o090lUnFpjGC6IjKuwbB6vejeAQapLSmK28DfhMLpemyy8lzH5wNGY4js6je8CbmwfySrVI6V9WZkQfgYAXeUGAj9ayOY3BqRvEPhx2OLaRBFNWNhSSB0XyTQB5oAds2AcZAtD3I9sN/cNnJzRPw5Tpi10OdwEPg=
  skip_cleanup: true
  file: lt.tar.gz
  on:
    repo: qgustavor/node-languagetool-service
